package br.uniriotec.testeimovel.wsimovel;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Sat Oct 01 20:02:24 BRT 2011 
 */

public class ImovelService_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements br.uniriotec.testeimovel.wsimovel.ImovelService, /**/java.io.Serializable
{

  public ImovelService_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, br.uniriotec.testeimovel.wsimovel.ImovelService.class, service);
  }
  
    
  /**
   * Operation Name : {http://br/uniriotec/services}getImoveis   */

  public br.uniriotec.tabd2.imovel.LstImovel getImoveis(java.lang.String bairro,java.lang.String cidade) throws java.rmi.RemoteException {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(bairro);
        _args.add(cidade);
    
    try {
            java.lang.Object _result = _invoke("getImoveis", _args.toArray());
      return (br.uniriotec.tabd2.imovel.LstImovel)_result;
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  }  public void getImoveisAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String bairro,java.lang.String cidade) throws java.rmi.RemoteException  {
    java.util.ArrayList _args = new java.util.ArrayList();

    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY, "true");
    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY, apc);
    _setProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY, "getImoveis");
    _setProperty(weblogic.wsee.async.AsyncConstants.OPERATION_NAME_PROPERTY,
                 "getImoveis");
    _setProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY, "br.uniriotec.tabd2.imovel.LstImovel");
    _args.add(bairro);
        _args.add(cidade);
    
    try {
      java.lang.Object _result = _invoke("getImoveis", _args.toArray());
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
    finally {
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY);

    }
  }
   
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("ImovelServiceSoapPort", "ImovelServiceSoapPort");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "br.uniriotec.testeimovel.wsimovel.ImovelServiceService",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}