package br.uniriotec.testeimovel.wsimovel;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Sat Oct 01 20:02:24 BRT 2011  
 */

public interface ImovelServiceService extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ImovelServiceSoapPort  
     // Port Type: ImovelService   
     //***********************************
     
  /**
   * returns ImovelServiceSoapPort port in this service 
   */
  br.uniriotec.testeimovel.wsimovel.ImovelService getImovelServiceSoapPort() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getImovelServiceSoapPort(byte[] username, byte[] password);
   */
  br.uniriotec.testeimovel.wsimovel.ImovelService getImovelServiceSoapPort(String username, String password) throws javax.xml.rpc.ServiceException;

  br.uniriotec.testeimovel.wsimovel.ImovelService getImovelServiceSoapPort(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }