package br.uniriotec.testeimovel.wsimovel;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Sun Oct 02 17:15:22 BRT 2011  
 */

public interface ImovelService extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://br/uniriotec/services}getImoveis   */

  public br.uniriotec.tabd2.imovel.LstImovel getImoveis(java.lang.String bairro,java.lang.String cidade) throws java.rmi.RemoteException;
    public void getImoveisAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String bairro,java.lang.String cidade) throws java.rmi.RemoteException ;
  
}